#data base properties 
db:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "root123"
  
  
#soap web service call

soap:
  wsdl: "http://mu.mulesoft-training.com:80//essentials/delta?wsdl"